[2025-10-23T09:17:57.384+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-23T09:17:57.399+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_neo4j_from_gold.load_neo4j manual__2025-10-23T09:17:56.903024+00:00 [queued]>
[2025-10-23T09:17:57.402+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_neo4j_from_gold.load_neo4j manual__2025-10-23T09:17:56.903024+00:00 [queued]>
[2025-10-23T09:17:57.402+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-23T09:17:57.407+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): load_neo4j> on 2025-10-23 09:17:56.903024+00:00
[2025-10-23T09:17:57.411+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=2889) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-23T09:17:57.411+0000] {standard_task_runner.py:64} INFO - Started process 2890 to run task
[2025-10-23T09:17:57.411+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_neo4j_from_gold', 'load_neo4j', 'manual__2025-10-23T09:17:56.903024+00:00', '--job-id', '294', '--raw', '--subdir', 'DAGS_FOLDER/load_neo4j_from_gold.py', '--cfg-path', '/tmp/tmp16kw2bak']
[2025-10-23T09:17:57.412+0000] {standard_task_runner.py:91} INFO - Job 294: Subtask load_neo4j
[2025-10-23T09:17:57.437+0000] {task_command.py:426} INFO - Running <TaskInstance: load_neo4j_from_gold.load_neo4j manual__2025-10-23T09:17:56.903024+00:00 [running]> on host c48d41bd1c66
[2025-10-23T09:17:57.496+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_neo4j_from_gold' AIRFLOW_CTX_TASK_ID='load_neo4j' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T09:17:56.903024+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T09:17:56.903024+00:00'
[2025-10-23T09:17:57.497+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-23T09:17:57.503+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-23T09:17:57.504+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/load_neo4j_from_gold.py --uri bolt://kg_neo4j:7687 --nodes /opt/***/data/gold/nodes.csv --edges /opt/***/data/gold/edges.csv --batch 20000']
[2025-10-23T09:17:57.508+0000] {subprocess.py:86} INFO - Output:
[2025-10-23T09:17:57.935+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-23T09:17:57.935+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/load_neo4j_from_gold.py", line 12, in <module>
[2025-10-23T09:17:57.935+0000] {subprocess.py:93} INFO -     from neo4j import GraphDatabase
[2025-10-23T09:17:57.936+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'neo4j'
[2025-10-23T09:17:57.964+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-23T09:17:57.964+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-23T09:17:57.973+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-23T09:17:57.976+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=load_neo4j_from_gold, task_id=load_neo4j, run_id=manual__2025-10-23T09:17:56.903024+00:00, execution_date=20251023T091756, start_date=20251023T091757, end_date=20251023T091757
[2025-10-23T09:17:57.981+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 294 for task load_neo4j (Bash command failed. The command returned a non-zero exit code 1.; 2890)
[2025-10-23T09:17:58.014+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-23T09:17:58.024+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-23T09:17:58.024+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
