[2025-10-23T09:33:17.495+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-23T09:33:17.514+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_neo4j_from_gold.load_neo4j manual__2025-10-23T09:33:16.431693+00:00 [queued]>
[2025-10-23T09:33:17.517+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_neo4j_from_gold.load_neo4j manual__2025-10-23T09:33:16.431693+00:00 [queued]>
[2025-10-23T09:33:17.518+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-23T09:33:17.525+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): load_neo4j> on 2025-10-23 09:33:16.431693+00:00
[2025-10-23T09:33:17.530+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=3216) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-23T09:33:17.530+0000] {standard_task_runner.py:64} INFO - Started process 3217 to run task
[2025-10-23T09:33:17.534+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_neo4j_from_gold', 'load_neo4j', 'manual__2025-10-23T09:33:16.431693+00:00', '--job-id', '296', '--raw', '--subdir', 'DAGS_FOLDER/load_neo4j_from_gold.py', '--cfg-path', '/tmp/tmpd4rd3oat']
[2025-10-23T09:33:17.537+0000] {standard_task_runner.py:91} INFO - Job 296: Subtask load_neo4j
[2025-10-23T09:33:17.591+0000] {task_command.py:426} INFO - Running <TaskInstance: load_neo4j_from_gold.load_neo4j manual__2025-10-23T09:33:16.431693+00:00 [running]> on host c48d41bd1c66
[2025-10-23T09:33:17.644+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_neo4j_from_gold' AIRFLOW_CTX_TASK_ID='load_neo4j' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T09:33:16.431693+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T09:33:16.431693+00:00'
[2025-10-23T09:33:17.645+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-23T09:33:17.652+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-23T09:33:17.653+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/load_neo4j_from_gold.py --uri bolt://kg_neo4j:7687 --nodes /opt/***/data/gold/nodes.csv --edges /opt/***/data/gold/edges.csv --batch 20000']
[2025-10-23T09:33:17.657+0000] {subprocess.py:86} INFO - Output:
[2025-10-23T09:33:18.052+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-23T09:33:18.052+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/load_neo4j_from_gold.py", line 12, in <module>
[2025-10-23T09:33:18.053+0000] {subprocess.py:93} INFO -     from neo4j import GraphDatabase
[2025-10-23T09:33:18.053+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'neo4j'
[2025-10-23T09:33:18.086+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-23T09:33:18.087+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-23T09:33:18.097+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-23T09:33:18.099+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=load_neo4j_from_gold, task_id=load_neo4j, run_id=manual__2025-10-23T09:33:16.431693+00:00, execution_date=20251023T093316, start_date=20251023T093317, end_date=20251023T093318
[2025-10-23T09:33:18.107+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 296 for task load_neo4j (Bash command failed. The command returned a non-zero exit code 1.; 3217)
[2025-10-23T09:33:18.126+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-23T09:33:18.140+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-23T09:33:18.141+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
